# Generated by Django 4.0.1 on 2022-01-16 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcourses',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allcourses', to=settings.AUTH_USER_MODEL),
        ),
    ]
